spring.application.name=stanzaApp

#DB Configuration:
spring.datasource.url=jdbc:postgresql://localhost:5432/StranzaAppDB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

stripe.secret.key=sk_test_51U239N1Bt2CZLCgNSuugdMoo0qWHlu6g8I245FguOGmpwp9uryvecE5QJUqX30Gae2LhQ6U26hqVUtVYh4kqbUZa00FtvFldB7
stripe.webhook.secret=whsec_59e8c63ad5ad249746c0d52da58b90f6476100beb86932dca475047e9bb328b9

spring.datasource.username=virajalmeida
spring.datasource.password=

server.servlet.context-path=/api/v1

jwt.secretKey=dfgyt655r6tygyu7y768uy86g646568ubte4w32456h7j89kminhyjuinu875
frontend.url=http://localhost:3000
