spring.application.name=stanzaApp

#DB Configuration:
spring.datasource.url=jdbc:postgresql://localhost:5432/StranzaAppDB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.username=virajalmeida
spring.datasource.password=

server.servlet.context-path=/api/v1